### ISSUE TITLE
Problem in the rendering of geometric shapes

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#67]
Hi!
The geometric tool is cool, but there remain some weird behaviors when using it.

1. draw a rectangle (say) with mouse or stylus
1. press m key to magnetize it
1. press m key to fix it: the rectangle has disappeared! (at least its border)
1. click left mouse button (not stylus !) and the rectangle reappears!

Strangely enough (but I think this second issue is linked to the first one) even if you *delete* the magnet rather than to *fix* it, the overall process is the same: the rectangle disappears (ok) and finally reappears (not ok).

As the late Mr Cyclopède said: « Étonnant, non ? » ;-)

**Comment by francoisschwarzentruber** [comment]
Dear Pierre Desproges,
thank you for pointing that issue. It is solved now.

PS: I forgot to compute the new drawing shape during the mousedown event. Therefore, the previous shape was shown instead of the new one. I just added that computation to solve that issue.

**Comment by philardine** [comment]
Sigh! I have been identified!
Nevertheless, It seems to me that only the last point (4) has been solved: clicking the left mouse doesn't make the rectangle reappear. The weird point 3 is still present... or I missed something?

**Comment by francoisschwarzentruber** [comment]
Dear M. Cyclopède,
I think step 3 is normal. At step 2, when you magnetize a rectangle, the drawn rectangle disappears, and a magnet of the form of a rectangle appears. The magnet contains an image but does not contain the rectangle in that. Therefore at step 3, only the image inside the magnet is drawn on the board, and not the rectangle.
Would you expect the rectangle to be part of the magnet? I guess sometimes it is relevant, sometimes not. What is your use?

PS: I usually have the following use of magnets: to move objects that are drawn, but I do not want the contour I draw to be part of it.

**Comment by philardine** [comment]
Of course! Thank you to remind me the philosophy of magnets!
If I want to move my rectangle (e.g. a UML class) I just have to draw a line around it, and not try to magnetize it. Silly me, I knew it though!

**Comment by francoisschwarzentruber** [comment]
Yes, currently, the philosophy of magnets is like this. But maybe we can change/modify/extend its philosophy in order to fit more other uses:
- we could imagine special magnets for UML classes, etc.
- we could imagine magnets on which we can draw
- we could imagine a function to add a border to magnets
The challenge is to continue to follow the KISS principle ("keep it simple, stupid").

Thank you for having pointed out that the current philosophy is not suitable for all uses.

**Comment by francoisschwarzentruber** [comment]
It remains KISS yes :). Thank you for your nice suggestions. To sum up your idea:
- "m" => magnetize but the border is not there
- "shift + m" => magnetize with the border
Right?

**Comment by philardine** [comment]
Absolutely! :-)

**Comment by francoisschwarzentruber** [comment]
OK! :) Also:
- "m" or "Ctrl + X" => magnetize but the border is not there
- "shift + m" or "Ctrl + Shift + X"  => magnetize with the border
- "Ctrl + C" => magnetize but the border is not there, and also keep what is on the border
- "Ctrl + Shift + C" => magnetize with the border, and also keep what is on the border

Why not. Another solution would be to have an option to add a border to an existing magnet?

**Comment by philardine** [comment]
OK for the first part of your answer, this would make the use of shortcuts more consistent.

For the second part (adding border to existing magnet), as far as I can imagine its usage, I think I prefer the first solution: wouldn't it be boring to always add the border each time you duplicate the magnet?

**Comment by francoisschwarzentruber** [comment]
I agree with you. I added these shortcuts.
PS: I agree with you. "Adding a border to existing magnet" will be a functionality that people will not understand.
